[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = 'ó° … '
style = 'blue bold'

[golang]
format = 'via [$symbol($version )($mod_version )]($style)'

[nodejs]
disabled = true

[direnv]
disabled = false
format = "[$symbol$loaded+$allowed]($style) "
symbol = "ğŸƒ "
style = "bold bright-green"

[localip]
disabled = false

[kubernetes]
disabled = false
